### ISSUE TITLE
Fonts in SVG

### ISSUE THREAD

**Issue by SamuelJoly** [ACE-IoT-Solutions/ace-svg-react#10]
I think browsers like Chrome or Firefox don't support fonts for SVG, but can we use fonts in this plugin? If we can, where do we drop the font file? Thanks

**Comment by ilayn** [comment]
I don't know if it helps you but if it is hosted online you can just point to it. For example for google fonts you can use `@import` That is to say, you can place 

```html
<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,500;1,100&display=swap');
</style> 
```
in your SVG document which downloads multiples styles of Roboto on the fly.
