### ISSUE TITLE
Manual install of plugin

### ISSUE THREAD

**Issue by Drex0** [ACE-IoT-Solutions/ace-svg-react#12]
My Grafana instance is not connected to the web, I have to manually install my plugins by downloading the zip on a separate pc and sticking it into the plugin folder. This plugin's editor window just shows 'loading..', I'm guessing it doesn't have the dependencies. Can I load these manually as well? Do I need to build it?

![Capture](https://user-images.githubusercontent.com/22973842/104355867-82d32480-54c8-11eb-9536-3fd9530e07fe.PNG)

**Comment by acedrew** [comment]
@evannorton Can you check out this install method? It's not too uncommon, especially in OT systems.

**Comment by henjoe** [comment]
Bus is it gonna still work without the internet? for example, I did a lot of coding stuff (while connected to internet on my testing machine), after that, I need to import my dashboard to the production machine (which has no internet), my question is, is it still gonna work on my production machine?

**Comment by acedrew** [comment]
Yes, if you build the monaco into the dist yourself, it will not attempt to
collect it from the CDN.

**Comment by acedrew** [comment]
@henjoe were you able to resolve this?

**Comment by henjoe** [comment]
I tried to diaconnect it on internet and I can still use the editor.

**Comment by acedrew** [comment]
@henjoe Awesome, thank you!
