### ISSUE TITLE
Adding all element IDs not working

### ISSUE THREAD

**Issue by kgroshert** [ACE-IoT-Solutions/ace-svg-react#13]
I am trying to use "Add all SVG element IDs" on a large SVG document (2MB, 160 rects with id).
When pushing the button nothing happens. It works fine with simpler SVGs.

Is there anything I can do to debug this?

**Comment by acedrew** [comment]
Anything you can provide from console would be great, if there are errors.
I've not tried any SVG documents that large, so there may just be some limits in the SVG.js code. That's a lot of work, and while we use the React API, SVG rendering doesn't benefit from the virtual DOM so the performance is still somewhat limited.

You can also access the svgnode from the console and manually verify the IDs are getting parsed into the SVG.js object correctly.

**Comment by acedrew** [comment]
Closing due to no follow up.
