### ISSUE TITLE
Number of series at Java script interpreter

### ISSUE THREAD

**Issue by adelvalle62** [ACE-IoT-Solutions/ace-svg-react#19]
What is the best strategy for variables (as series) at JavaScript interpreter, I couldn’t get more than 19 ones, is it possible to get more?

regards and thanks in advance

**Comment by acedrew** [comment]
@adelvalle62 I'm not sure I understand your question. There's no limit that I know about. Are you talking about 19 individual queries in the query editor? Are you talking about being able to print them in the console? Hopefully can point you in the right direction, but not sure what you're referring to.

**Comment by acedrew** [comment]
No response to follow up questions, closing

**Comment by adelvalle62** [comment]
There was an Issue with versions before 8.1.1 of Grafana, but now it's solved thanks
