### ISSUE TITLE
Example provided does not work. It only works if 'context' is changed into 'option'

### ISSUE THREAD

**Issue by miq28** [ACE-IoT-Solutions/ace-svg-react#29]
Hi,

Awesome plugin guys 👍, I'm coming from a previous snap.svg plugin user and this plugin is big step-up!

I am on Grafana 8.3.3 and I installed the plugin using grafana-cli. 
I cannot make the provided example to work unless I change the `context` into `options` in both Init and Render section.

I changed this
`context.animateLogo`

into this
` options.animateLogo`

Can you help.. am I missing something..?

![Animation](https://user-images.githubusercontent.com/92211442/149475116-7aec78bd-266a-43c5-b976-fce22b17f9ac.gif)

**Comment by acedrew** [comment]
This could be as simple as a mistake in the example code, @evannorton can you take a look and update the example to match the current implementation?

Andrew

**Comment by evannorton** [comment]
> This could be as simple as a mistake in the example code, @evannorton can you take a look and update the example to match the current implementation?
> 
> Andrew

For sure!
