### ISSUE TITLE
Data links option has no effect

### ISSUE THREAD

**Issue by slickArgonian** [ACE-IoT-Solutions/ace-svg-react#31]
Hello,

I am trying to create a data link with the option in the side panel because I need to use data from the query. However, this doesn't have any effect. On other base panels (stat for eample), adding a data link directly provides a link when hovering over the whole panel.

Is this intentional ? 

Also, props for the amazing hand-on documentation !

**Comment by nicfv** [comment]
Hi! Are you referring to a hyperlink that directs you to another website/dashboard?

**Comment by nicfv** [comment]
Closing out this issue due to lack of activity. If you need more help, please feel free to open a new one!
