### ISSUE TITLE
Can't install the plugin (via docker)

### ISSUE THREAD

**Issue by patriziomadferitmilione** [ACE-IoT-Solutions/ace-svg-react#32]
I'm running grafana from a Docker container, so I don't have the chance to download the plugin in and extract it directly in my plugins directory, when I try to install it through the cli, I get this error, any ideas on a solution?

$ grafana-cli plugins install aceiot-svg-panel
installing aceiot-svg-panel @ 0.0.11
from: https://grafana.com/api/plugins/aceiot-svg-panel/versions/0.0.11/download
into: /var/lib/grafana/plugins

Error: ✗ failed to extract plugin archive: failed to extract file: failed to open file: open /var/lib/grafana/plugins/aceiot-svg-panel/CHANGELOG.md: no such file or directory

**Comment by nicfv** [comment]
Can you please try this in the newest version of the plugin and open a new issue if it is still happening? `0.1.0`
