### ISSUE TITLE
How to create a clickable svg group that passes the id to javascript?

### ISSUE THREAD

**Issue by Drex0** [ACE-IoT-Solutions/ace-svg-react#37]
Is there a way to create an onclick event inside an svg group and pass the id to a javascript function with this panel? I would like to know which group was clicked and then open another dashboard with the variables passed in for templating. 

I have been hard coding an `<a href=""><g></a>` around my group and it seems to work. Just a lot of manual effort.

**Comment by acedrew** [comment]
If you give your group an ID, you can assign that id manually in the SVGMappings and everything will work just like any other mapped element.
