### ISSUE TITLE
accessing SVG elements by name

### ISSUE THREAD

**Issue by bijwaard** [ACE-IoT-Solutions/ace-svg-react#64]
I'm trying to get my phasor plot working with React that used to work with the Angular SVG plugn, importing the SVG worked fine.
![image](https://github.com/ACE-IoT-Solutions/ace-svg-react/assets/6523124/ad4a3a9c-7edd-412b-a35c-be876279d536)

I have the following id's for labels in my SVG (and similar for other repeating elements like circles):

- label0
- label20
- label40
- label60
- label80
- label100

With the older SVG plugin I could fetch them in a loop like this in onInit():

```
var labels=[];
for (i = 1; i < 6; i++) {
    labels.push(svgnode.getElementById("label"+(i*20)));
}
```
However svgnode.getElementsById does no longer seem to work in this plugin, is there another way to fetch the svg elements by ID?

I tried to map them with the plugin I get something like this:
![image](https://github.com/ACE-IoT-Solutions/ace-svg-react/assets/6523124/3a208722-b6d4-46c1-ad21-2836657e884d)

Another issue is that I cannot map all SVG elements, because some of them are in the background of others.

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Got further by manually creating other maps, and creating arrays of SVG nodes in the initialisation as follows:

```
options.labels=[svgmap.label0,svgmap.label20,svgmap.label40,svgmap.label60,svgmap.label80,svgmap.label100];
console.log("#labels="+options.labels.length)
options.line=[svgmap.L1,svgmap.L2,svgmap.L3,svgmap.L4];
console.log("#line="+options.line.length)
```

However, when I try to update a line via JS Render, it gives the following exception:

```
console.log("#line="+options.line.length);
options.line[3].attr({"x2" : 100,"y2" : 100});
```

```
#line=4

User event code failed: TypeError: options.line[3] is undefined
    anonymous 484.805ce326eee3d290c3d9.js line 1099 > eval line 1 > Function:12
    renderSVG ACESVGjsPanel.tsx:240
    ref ACESVGjsPanel.tsx:269
    React 14
    triggerForceUpdate PanelEditor.tsx:121
    RxJS 3
    d EventBus.ts:38
    emit index.js:181
    publish EventBus.ts:28
    updateOptions PanelModel.ts:301
    onPanelOptionsChanged PanelEditor.tsx:172
    onChange getVisualizationOptions.tsx:94
    onChange getVisualizationOptions.tsx:340
    onBlur CodeEditor.tsx:78
    React 11
ACESVGjsPanel.tsx:249:16
    renderSVG ACESVGjsPanel.tsx:249
    ref ACESVGjsPanel.tsx:269
    React 14
    triggerForceUpdate PanelEditor.tsx:121
    RxJS 3
    d EventBus.ts:38
    emit index.js:181
    publish EventBus.ts:28
    updateOptions PanelModel.ts:301
    onPanelOptionsChanged PanelEditor.tsx:172
    onChange getVisualizationOptions.tsx:94
    onChange getVisualizationOptions.tsx:340
    onBlur CodeEditor.tsx:78
    React 11

```

Kind regards,
Dennis

**Comment by nicfv** [comment]
I would need to have a copy of your SVG file to verify, but it appears that `svgmap.L3` is undefined. Do you have a `<path>` in your SVG called `L3`?

**Comment by bijwaard** [comment]
Hi Nic,
Thanks for looking into this. L3 is a marker that includes a path. My labels and L3 look as follows in SVG:
```
<svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 200 220" >
<defs>
      <marker id="markerArrowBlue" markerWidth="3" markerHeight="3" refX="1.5" refY="1.5" orient="auto">
          <path d="M1,0 L1,3 L2,1.5 L1,0" style="fill: blue" />
      </marker>
</defs>
  <text id="label100" x="100" y="200" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">5</text>
  <text id="label80" x="100" y="180" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">4</text>
  <text id="label60" x="100" y="160" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">3</text>
  <text id="label40" x="100" y="140" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">2</text>
    <text id="label20" x="100" y="120" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">1</text>
  <text id="labels0" x="100" y="100" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">0</text>
      <line x1="100" y1="100" x2="100" y2="5"  style="stroke-width: 4px; stroke: blue;marker-end: url(#markerArrowBlue);"   id="L3"/>
</svg>
```

**Comment by nicfv** [comment]
Option 1: Looking at this more closely I think it's a very simple fix. Add an SVG mapping from `L3` to `L3`. That's the best way to do it.

Option 2: If you wanted to achieve this without the mapping, you could access the DOM using the [`find()`](https://svgjs.dev/docs/3.2/referencing-creating-elements/) methods. Here's an example what you could do:


### User JS Render Code

```js
const L3 = svgnode.findOne('#L3');
// Use any SVG.js methods
L3.rotate(3);
```

I'll work on getting this 2nd case documented somewhere.

I appreciate your patience - I'm also learning as I go! Let me know if this solved your problem.
