### ISSUE TITLE
Aiven support

### ISSUE THREAD

**Issue by heatweb** [ACE-IoT-Solutions/ace-svg-react#71]
Not supported by Aiven.
Please help... by voting for it to be supported.

Thanks for reaching out to Aiven Support today.  
At this current time there is no immediate plan to add support of this plugin to the Aiven platform however, I have submitted this as an idea to our ideas portal to gather interest on your behalf: https://ideas.aiven.io/forums/951283-observability/suggestions/47151595-ace-svg-plugin. If we find that there is high interest in this, our product team will then look at refining and adding this to our road map. 
 Please let me know if there is anything further we can assist you with today.

**Comment by nicfv** [comment]
Thank you for your suggestion! I'm not familiar with Aiven, but I will definitely take this into consideration as this project continues through development. For now, feel free to use it on [Grafana](https://grafana.com/grafana/) - which is free and open source to download.
